name: daily_version_check
on:
  workflow_dispatch:
  schedule:
  - cron:  '30 16 * * *'
jobs:
  daily_version_check:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: get swagger-ui-dist version
      run: |
        VERSION=`curl -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" 'https://api.github.com/repos/swagger-api/swagger-ui/releases?per_page=1' | jq -r '.[].tag_name'`
        SWAGGER_VERSION=${VERSION:1}
        echo "SWAGGER_VERSION=$SWAGGER_VERSION" >> $GITHUB_ENV
        echo "SWAGGER VERSION $SWAGGER_VERSION" >> $GITHUB_STEP_SUMMARY
        echo $SWAGGER_VERSION
    - name: crate version
      run: |
        CRATE_VERSION=`grep '^version =' Cargo.toml | cut -d'"' -f 2`
        echo "CRATE_VERSION=$CRATE_VERSION" >> $GITHUB_ENV
        echo "CRATE VERSION BEFORE RUN $CRATE_VERSION" >> $GITHUB_STEP_SUMMARY
        echo $CRATE_VERSION
    - name: replace version
      if: env.CRATE_VERSION != env.SWAGGER_VERSION
      run: |
        sed -i "s/version \= \"$CRATE_VERSION\"/version \= \"$SWAGGER_VERSION\"/" Cargo.toml
        cat Cargo.toml
    - name: Replace assets
      run: |
        curl "https://raw.githubusercontent.com/swagger-api/swagger-ui/v${SWAGGER_VERSION}/dist/swagger-ui-bundle.js" -o assets/swagger-ui-bundle.js
        echo "got swagger-ui-bundle.js"
        curl "https://raw.githubusercontent.com/swagger-api/swagger-ui/v${SWAGGER_VERSION}/dist/swagger-ui-bundle.js.map" -o assets/swagger-ui-bundle.js.map
        echo "got swagger-ui-bundle.js.map"
        curl "https://raw.githubusercontent.com/swagger-api/swagger-ui/v${SWAGGER_VERSION}/dist/swagger-ui.css" -o assets/swagger-ui.css
        echo "got swagger-ui.css"
        curl "https://raw.githubusercontent.com/swagger-api/swagger-ui/v${SWAGGER_VERSION}/dist/swagger-ui.css.map" -o assets/swagger-ui.css.map
        echo "got swagger-ui.css.map"
        ls -lisat assets
    - name: Build artifact
      if: env.CRATE_VERSION != env.SWAGGER_VERSION
      uses: actions-rs/cargo@v1
      with:
        command: build
    - uses: stefanzweifel/git-auto-commit-action@v5
      if: env.CRATE_VERSION != env.SWAGGER_VERSION
      with:
        commit_message: Version bump.
        file_pattern: 'Cargo.* assets/*'
    # - run: cargo publish
    #   if: env.CRATE_VERSION != env.SWAGGER_VERSION
    #   env:
    #     CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
